### ISSUE TITLE
Misplacement of buttons when selection is near to the right edge

### ISSUE THREAD

**Issue by jonathanmv** [daviferreira/medium-editor#138]
If the browser window is narrow and the selection occurs near to the right side, the buttons get misplaced as shown in the screenshot
![image](https://f.cloud.github.com/assets/86024/2052962/45aed2c0-8a9f-11e3-80f0-99dbf4973fb6.png)

This doesn't happen on the left side
![image](https://f.cloud.github.com/assets/86024/2052976/86196424-8a9f-11e3-9fcd-5743ed2d2b76.png)

**Comment by nmielnik** [comment]
This is now fixed in the code itself, it will avoid wrapping the buttons unless the viewport itself is not wide enough to fit the toolbar.
