### ISSUE TITLE
Can you provide an example of how to use .deactivate() and .activate() APIs?

### ISSUE THREAD

**Issue by chanpory** [daviferreira/medium-editor#139]
I am a bit new to this library, and would love to better understand how I should use .deactivate() and .activate(). Thank you.

**Comment by nmielnik** [comment]
`activate()` and `deactivate()` have been replaced by `setup()` and `destroy()`.

Also, we should have a bit better documentation now.

I'll open @dodyg 's feedback in a separate issue.
