### ISSUE TITLE
IE11 underline/strong/italic etc. buttons are not showing their active states.

### ISSUE THREAD

**Issue by daviferreira** [daviferreira/medium-editor#158]
Buttons are not preserving active states.

**Comment by nmielnik** [comment]
Currently working on a fix for this which would allow for multiple element types (ie `<b>` vs `<strong>`, `<i>` vs `<em>`) as well as look at computed styles to decide whether to 'activate' the button in the toolbar

**Comment by nmielnik** [comment]
This should be fixed in #404
