### ISSUE TITLE
Provide change events

### ISSUE THREAD

**Issue by bergie** [daviferreira/medium-editor#17]
When binding the editor to an application (in this case [Create.js](http://createjs.org)), it would be helpful to receive *change* events to know when the contents have been modified (whether by text input or a formatting change).

Examples of how we get these events from other editors:

https://github.com/bergie/create/blob/master/src/editingWidgets/jquery.Midgard.midgardEditableEditorCKEditor.js#L35
https://github.com/bergie/create/blob/master/src/editingWidgets/jquery.Midgard.midgardEditableEditorHallo.js#L48
https://github.com/bergie/create/blob/master/src/editingWidgets/jquery.Midgard.midgardEditableEditorRedactor.js#L50
https://github.com/bergie/create/blob/master/src/editingWidgets/jquery.Midgard.midgardEditableEditorTinyMCE.js#L38

**Comment by nmielnik** [comment]
@bergie we now have a 'contentEditable' event that fires when the content has changed, this is supported in all our browsers as well.

You can subscribe to this custom event via the `subscribe()` method:
```javascript
var editor = new MediumEditor('.editor',);
editor.subscribe('editableInput', function (event, editorElement) {
  // event handling here
});
```

@beshur we have optional `onShowToolbar` and `onHideToolbar` callbacks that can be passed in as options when instantiating the editor.  These will be called each time the toolbar is shown and displayed:

```javascript
var editor = new MediumEditor('.editor', {
  onShowToolbar: function () { // handling show },
  onHideToolbar: function () { // handling hide }
});
```

Now that you mention it, it seems like this should be a custom event, I'll look into supporting this in the future.
