### ISSUE TITLE
Pluggable actions

### ISSUE THREAD

**Issue by daviferreira** [daviferreira/medium-editor#2]
Create a pluggable template for button actions and convert medium default actions to the new standard (yet to be defined, something like a JS object with pre-defined methods like label, icon, action, etc.).

**Comment by nmielnik** [comment]
This has been around for a while now :smile:

**Comment by daviferreira** [comment]
![https://braws.slack.com/emoji/pogchamp/3b3e75ad154e6384.png](https://braws.slack.com/emoji/pogchamp/3b3e75ad154e6384.png)
