### ISSUE TITLE
font-face use / problems removing markup

### ISSUE THREAD

**Issue by bbnnt** [daviferreira/medium-editor#210]
had one weird problem on some project.

For some tags (b and sup mainly), it is possible to add the styling form the toolbar.
Problem is, now way to remove it by clicking again on the enable button in the toolbar : i click on B for bold, I can add it, but can't remove it… no way. Except to suppress the enclosed word.

Looking at it from the console; I removes it and re-add it right away (I'm saying this, seeing a quick clipping in the markup)

-- 

I added a custom font to style the editable content (as far as the demo shows it, no problem doing it). So for a bold; I set the font-weight at normal, and specify the bold font in my css.

Removing the font-weight, it works like a charm.

--

So I checked the demo again. There's a font-weight:bold set to the bold markup (so far, quite logical), and the font is set to ProximaNovaBlack.

Cool thing is, adding font-weight bold on proxima-nova makes it look a little heavier than it should be (we're getting a proximanovaSUPERBLACK though), but does not makes it ugly.

--

Problem is, adding font-weight-bold (as it is not useful, can we say it is wrong ?) makes most of the font-faces look ugly (as you could understand, my current problem… which should be a concern I think for the too-many web designers that add some bold to a font-face)

--

I wonder how the js has concerns with the styling.

It would surely make the plugin a lot more perfect than it already is.
This plugin is dedicated to text, how could we go a little further on this one ?
I'd be very happy to do something on this one, any entry points to understand the logic in your code, where it happens and could be improved ?

--
For the \<sup\> tag, that might the same problem…

**Comment by nmielnik** [comment]
The suggestion @yacomink added here seems to be a sufficient work around for the issue.

As long as we're relying on contenteditable, we'll be relying on the browser to decide whether text is bold or not and to do what it needs to do to bold or unbold it.  When there's CSS on the page that changes the weight of fonts, there will likely be so issues with bolding/unbolding via medium-editor.

You can also remove the bold button from the toolbar if you're using a font that will be ugly when bolded.

**Comment by bbnnt** [comment]
@nmielnik yes I'll sure remove it as this problem was based on this specific need

I can understand google or typekit can fool people and make them think that switching from a regular font to a bold one can be as easy as specifying "font-weight: bold" in a css rule, but it is far from being standard

"When there's CSS on the page that changes the weight of fonts" : is contenteditable changing the css ?
when using font-faces, you always keep it all regular. Correct me if I'm wrong, what's displayed by medium-editor is controlled by css right ?

**Comment by nmielnik** [comment]
medium-editor uses the built in `document.exexCommand()` to make text bold/unbold, and `document.queryCommandState()` to ask the browser if the current selection is bold or not.

For Chrome, Firefox, and Safari, this means wrapping the selection in `<b>` tags, and in IE this means wrapping the selection in `<strong>` tags, in the general case.  There are situations where it might add/remove a font weight if nested inside other tags that affect the font (ie a header tag).  Depending on what the computed style of the selection is, this can affect the return result of `document.queryCommandState()`, so enforcing various font weights can make the browser behave a bit inconsistent.
