### ISSUE TITLE
Adding support for autolink

### ISSUE THREAD

**Issue by ikhattab** [daviferreira/medium-editor#229]
Hi,

I'm working on adding support for autolink when user types/paste some url that looks like a valid url and press space after/before it, it should be converted to link, like this
![autolink](http://f.cl.ly/items/301K1n0q1q1K2y0Z2L2n/autolink.gif)

You can see what I did so far in https://github.com/ikhattab/medium-editor/tree/FEAT/autolink

I will submit pull request when I finished probably this weekend.

TODO:
- [ ] Adding support for converting link after/before pressing ENTER.
- [ ] Adding testes.

**Comment by nmielnik** [comment]
looks like we have a proposed implementation for autolink in #599

**Comment by nmielnik** [comment]
Now that #599 exists, auto-link is supported.  This should be released in v4.9.0 when that comes
