### ISSUE TITLE
MIT License?

### ISSUE THREAD

**Issue by tmcconechy** [daviferreira/medium-editor#237]
Would you consider a different license? The license as is does seem to pose some challenges with Legal situations as it is a little confusing where as MIT license is pretty widely acceptable on Legally. See: https://romanrm.net/beerware

I.E. If i fork and modify mine who gets the beer as the notice goes to the wrong author :) 

So, I think MIT license would get people using this more as the license is a little less questionable. And I'd gladly buy you a beer for this work :)

**Comment by leobalter** [comment]
@daviferreira, your project is awesome, and this license is funny, but it really doesn't work for forks, even for open source usage when it involves companies, etc. I would like to ask you to reconsider using an MIT (or similar) license. 

Regarding the beer, you might like using a pledgie badge or something similar. Like this [example](https://github.com/jzaefferer/jquery-validation/blob/master/README.md#help-the-project).

**Comment by daviferreira** [comment]
Alright, send a PR my way :)

I will miss the beerware license
