### ISSUE TITLE
How to get the editor instance when I am inside of an extension?

### ISSUE THREAD

**Issue by IonicaBizau** [daviferreira/medium-editor#246]
```js
...
extensions: {
    'myExtension': new MyExtension()
}
...
```

and:

```js
function MyExtension () {
    // how can I know in what Medium Editor instance is used
    // this instance of MyExtension?
}
```

**Comment by nmielnik** [comment]
There are now 2 ways to get the current medium-editor instance.

If you set the `this.parent` attribute to `true` when the extension is created, during initialization medium-editor will set the `this.base` property of the extension to be the current instance of MediumEditor.

```js
function MyExtension() {
    this.parent = true;
}
MyExtension.prototype.getButton = function () {
    return this.base.options.ownerDocument.createElement('button');  // this.base will be the MediumEditor instance
}
```

Alternatively, if you define an `init(instance)` method on your extension, MediumEditor will call that method and pass itself as the only argument:

```js
function MyExtension() { }
MyExtension.prototype.init = function (instance) {
    this.base = instance; // instance is the current MediumEditor instance
}
```
