### ISSUE TITLE
Should Anchor/Links update on blur?

### ISSUE THREAD

**Issue by mattgi** [daviferreira/medium-editor#254]
For anchors a user needs to click the link, enter text, and then hit Enter. If they hover/click off the toolbar, the link is not saved. Is this expected or should the anchor take effect on blur?

**Comment by nmielnik** [comment]
For editing things inside a popover, clicking outside of a dialog (generally) will close the dialog and not persist changes.  We have a 'Checkmark' button that behaves the same was as hitting enter in the keyboard.  Hitting 'escape' or clicking the 'x' will close the popover without persisting changes.

Based on what I've seen in most UX, I wouldn't want to persist the link change when clicking out.  This behavior wouldn't be difficult to implement as an override to the existing anchor extension, so for those who want this behavior I would handle that in a custom implementation I believe...let me know if anyone strongly disagrees.
