### ISSUE TITLE
Host on jsDelivr

### ISSUE THREAD

**Issue by jmagnusson** [daviferreira/medium-editor#272]
Would be nice to see medium-editor on [jsDelivr](http://www.jsdelivr.com/).

**Comment by j0k3r** [comment]
It could also be on https://cdnjs.com/

**Comment by daviferreira** [comment]
Our friend @IonicaBizau wrote a tool for it btw: https://github.com/IonicaBizau/cdnjs-importer :+1:

**Comment by IonicaBizau** [comment]
Hey, I can help with that! :smile:

**Comment by IonicaBizau** [comment]
I opened https://github.com/cdnjs/cdnjs/pull/4655. :four_leaf_clover: :sparkle:

**Comment by daviferreira** [comment]
:beers:

**Comment by j0k3r** [comment]
:+1:

**Comment by IonicaBizau** [comment]
@daviferreira Hehe, I never drunk beer, nor :coffee:! Water and natural juices are the best for me. :palm_tree: :smile:

**Comment by daviferreira** [comment]
![giphy](https://cloud.githubusercontent.com/assets/38787/7746451/ae917584-ffb2-11e4-9dc8-850030916041.gif)

**Comment by daviferreira** [comment]
@IonicaBizau could you please update our README when they merge :innocent:

**Comment by IonicaBizau** [comment]
@daviferreira BTW, I don't use the famous *f...* word. :smile: :smiley: 

Yeah, sure. I will update the readme with the cdn info. :+1:

**Comment by IonicaBizau** [comment]
@daviferreira  I opened #626. :dizzy:

**Comment by j0k3r** [comment]
Just a follow up for future versions, is this command is enough to upadte cdnjs?

```
$ cdnjs-importer -c path/to/cdnjs git@github.com:daviferreira/medium-editor.git
```

Where `path/to/cdnjs` is a clone of the cdnjs repo, right?

**Comment by IonicaBizau** [comment]
@j0k3r The new versions will be automatically updated on cdnjs when the package on npm will be updated (`npm publish`).

So, republishing on cdnjs doesn't make sense since the cdnjs-importer is smart and adds the autoupdate fields. :star2: 

> Where path/to/cdnjs is a clone of the cdnjs repo, right?

Yes, it's the local clone of cdnjs which defaults to `~/cdnjs`.

**Comment by j0k3r** [comment]
Great then!

But how long does it takes to be updated on cdnjs when it's up on npm?

The 4.10.2 is up on npm since few hours (https://www.npmjs.com/package/medium-editor) but nothing new on cdnjs (https://cdnjs.com/libraries/medium-editor)

**Comment by IonicaBizau** [comment]
@j0k3r It's supposed to be updated. The [cron job runs every 30 minutes](https://github.com/cdnjs/cdnjs/pull/4655#issuecomment-104232643).

/cc @PeterDaveHello

**Comment by PeterDaveHello** [comment]
Looks ok:
![Imgur](http://i.imgur.com/ufKF5HY.png)

**Comment by IonicaBizau** [comment]
@PeterDaveHello But the latest version on npm is `4.10.2` (the patch version is still `1` on cdnjs).

**Comment by PeterDaveHello** [comment]
oh, sorry, let me check it.

**Comment by PeterDaveHello** [comment]
I got your problem here, cronjob means the update from cdn repo to cdn and website, not from project repo to cdnjs repo, see :
https://github.com/cdnjs/cdnjs#enabling-gitrecommended-or-npm-auto-update
...

> won't be committed until one of our maintainers audit the updates

...
> it'll be reasonable to delay for at most 30 hours

**Comment by daviferreira** [comment]
Thank you for investigating, @PeterDaveHello

**Comment by j0k3r** [comment]
:arrow_right: https://github.com/jsdelivr/jsdelivr/pull/5064
