### ISSUE TITLE
Toolbar doesn't disappear immediately after deselecting text

### ISSUE THREAD

**Issue by hungle88** [daviferreira/medium-editor#287]
I tried to integrate this with one of my rails projects and this happens:
![untitled mov](https://cloud.githubusercontent.com/assets/2544327/4070863/3dfa054e-2e65-11e4-9f1e-f0d4df8c771e.gif)

Basically, when I select a piece of text, the toolbar immediately shows up as expected but when I click somewhere else (to deselect the text) it takes about ~500ms for the toolbar to disappear. Any idea why this happens?

I tried using the gem as well but got the same result. Also, it works fine on normal project and I only encounter this when trying to make it work in a rails project. Could this be some kind of conflict with other JS libraries? 

Thanks!

**Comment by nmielnik** [comment]
This hopefully should have improved after #361 and #365.  Would you be able to verify and potentially close this issue?

There will be some lag, but it should hopefully be much less noticeable (only 50ms)

**Comment by hungle88** [comment]
Hi @nmielnik 

Thanks for getting back to me. 
However, due to our timeline, we had to choose another solution for this :-(
Will save this for our next project, though.

Cheers!
