### ISSUE TITLE
Plans to add Medium-like separator ?

### ISSUE THREAD

**Issue by antoniobrandao** [daviferreira/medium-editor#292]
Are there any plans to include an option to add a simple horizontal separator like Medium does ?

It would make it look very classy. Separators are great to help understand different sections of a document.

I strongly suggest you guys go try edit a document in Medium.com, and see the separator in action, if you haven't yet.

**Comment by daviferreira** [comment]
Please, feel free to create an extension: https://github.com/daviferreira/medium-editor/wiki/Creating-Extensions
