### ISSUE TITLE
Tab Key for switching between paragraphs

### ISSUE THREAD

**Issue by aval12** [daviferreira/medium-editor#293]
Hi!
I'm not good at JS.
I created a listener for TAB-key press in my editor.
But is there a way to switch to the next paragraph, like in inputs in form?
I have written function for placing cursor at the end of element. But can not connect it with this script

**Comment by daviferreira** [comment]
You can set tabindex on the contenteditable.

**Comment by litera** [comment]
@daviferreira How would that help OP and his specific usage scenario?

**Comment by daviferreira** [comment]
Each ```p``` can be a contenteditable. Anyway, I don't think this should be a MediumEditor feature for now :smile:
