### ISSUE TITLE
Blockquote problem

### ISSUE THREAD

**Issue by caxopog** [daviferreira/medium-editor#294]
Hello

If i type 1 paragraph of text in editor and make it blockquote using editor button, i'll be unable to make non-blockquote paragraph, because "enter" makes new line in blockquote section, not new, non-blockquote paragraph.

Is there any way to make one of this:
1. Enter makes new paragraph not outside of blockquote block
2. After pressing blockquote button, new paragraph is appearing under the created blockquote

Thanks.

**Comment by nmielnik** [comment]
Fixed via #1162
