### ISSUE TITLE
Using font-awesome for save link

### ISSUE THREAD

**Issue by seifsallam** [daviferreira/medium-editor#297]
Is it possible to use font-awesome icon for saving instead of ✓? It would look much more consistent in style.

**Comment by denistsuman** [comment]
my awful but quick solution )

  $('.medium-editor-toobar-save').html('<i class="fa fa-check"></i>')
  $('.medium-editor-toobar-close').html('<i class="fa fa-times"></i>')
  $('.medium-editor-action-anchor').html('<i class="fa fa-link"></i>')
  $('.medium-editor-action-unorderedlist').html('<i class="fa fa-list-ul"></i>')
  $('.medium-editor-action-orderedlist').html('<i class="fa fa-list-ol"></i>')
  $('.medium-editor-action-justifyLeft').html('<i class="fa fa-align-left"></i>')
  $('.medium-editor-action-justifyCenter').html('<i class="fa fa-align-center"></i>')
  $('.medium-editor-action-justifyRight').html('<i class="fa fa-align-right"></i>')

**Comment by seifsallam** [comment]
@denistsuman Thanks :)
