### ISSUE TITLE
Errors on demo page

### ISSUE THREAD

**Issue by radmen** [daviferreira/medium-editor#299]
Demo page is opened via 'https' protocol, but assets are linked to 'http'. Due security reasons Chrome (v. 37.0.2062.122) doesn't want to open them.

![screenshot](https://i.imgur.com/JAgmH0U.png)

**Comment by daviferreira** [comment]
Where did you click that it opened as https? it should be http.

**Comment by radmen** [comment]
Well it is. Now I figured out it's a fault of *HTTPS Everywhere* extension. I think that in this case this issue can be closed.
