### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by bahadirarslan** [daviferreira/medium-editor#326]
Hi,

I have been developing a web site and looking for a text editor for a time. Firstly i had found ZenPen and realized it is not designed for web sites. After a few mails between Tim Holman, he suggested me, medium-editor.

Medium-editor is more suitable for a web site than ZenPen but i miss some features of ZenPen at Medium-editor such as dark mode. As i know, some people who loves writing heavily prefers to dark colors. 

Actually i am a backend developer so i couldn't edit css files correctly for dark mode. 
I thought may be you can consider adding such feature to Medium-editor.

Also full-screen support and auto save will be nice :)

Thanks for this great editor

**Comment by xaddict** [comment]
The default theme for medium-editor is dark.

The text it styles is according to your own website style. So a dark style would be something you need to implement in your site, not in the editor.

**Comment by nmielnik** [comment]
My feeling is these sort of things (which extend beyond the container of text that is being edited) should be controlled by the page, as we want medium-editor to be a way to edit text inline and not quite a way to style your page.
