### ISSUE TITLE
Switch Enter and Shift+Enter behaviour

### ISSUE THREAD

**Issue by caxopog** [daviferreira/medium-editor#333]
Hello, have one question:

How to switch editor behaviour?

Now:
Enter - new paragraph
Shift+Enter - new Line

I need:
Enter - new line
Shift+Enter - new paragraph

Tried a lot of things, but i d't similar with source code and i fail : (

**Comment by xaddict** [comment]
I would not make this configurable as it is the way every editor out there works (and should work), including the ridiculous Word.

**Comment by xaddict** [comment]
You could make containers optional though, like tinyMCE has, so enter doesn't wrap in <p> tags but <div>'s for example

**Comment by litera** [comment]
Hasn't this been discussed before? Enter/ShiftEnter are usual editor behaviours. Take Word for example. Works the same. Having these two switched would make it non-standard.

I suppose users should adopt to tools working as widely accepted standards than vice-a-versa...

**Comment by hellocosmin** [comment]
+1 @litera, doing this means moving away from the established functionality that is found in most (if not all) editors. Changing from <code>!e.shiftKey</code> to <code>e.shiftKey</code> is simple enough to not require a configurable option for something that is a particular need.

**Comment by daviferreira** [comment]
Alright :)
