### ISSUE TITLE
Not using this.on() when attaching click handler to contenteditable

### ISSUE THREAD

**Issue by nmielnik** [daviferreira/medium-editor#349]
I've noticed that the handy `this.on()` method is a great way to keep track of what event handlers have been attached, and allow for easily detaching everything when medium-editor is deactivated.

However, I noticed that a specific click handler for all contentEditable elements is not being attached using this.on, so medium-editor cannot detach it later.

See [here](https://github.com/daviferreira/medium-editor/blob/8aa0c8f9514289182bd1a49f856e086e34fa3596/src/js/medium-editor.js#L758)

Was there a specific reason for not using `this.on()` here?  Should this be changed to:

```
this.on('click', this.elements[i], this.checkSelectionWrapper);
```

**Comment by daviferreira** [comment]
I don't think there is a specific reason, it's just legacy code. If you could apply it everywhere would be nice :beers:

**Comment by nmielnik** [comment]
#358

**Comment by nmielnik** [comment]
![mediumeditor](https://cloud.githubusercontent.com/assets/2444240/8712185/1ed9688e-2b27-11e5-85ce-18299fb7b0fb.png)

**Comment by daviferreira** [comment]
wut
