### ISSUE TITLE
FEATURE REQUEST: Velocity.js - Accelerated JavaScript animation

### ISSUE THREAD

**Issue by comerc** [daviferreira/medium-editor#353]
http://julian.com/research/velocity/

**Comment by nchase** [comment]
obviously I have no authority here, but here's my opinion: velocity would be nice, but it might be weird to have a dependency on an animation library for a feature that some consumers of the library may not even use. the more agnostic thing to do here would be to have 'hooks' that a consumer can use to implement animation however they please.

**Comment by comerc** [comment]
this feature has to be optional, of course

**Comment by nchase** [comment]
@comerc: so do you want hooks for animations?
