### ISSUE TITLE
NS_ERROR_FAILURE Firefox

### ISSUE THREAD

**Issue by dylanjha** [daviferreira/medium-editor#354]
I'm seeing this exception: `NS_ERROR_FAILURENS_ERROR_FAILURE:`

at this line: https://github.com/daviferreira/medium-editor/blob/master/dist/js/medium-editor.js#L445

**Comment by nchase** [comment]
this doesn't seem to be happening on the demo page. can you provide a case/demo of where/how this happens?

**Comment by dylanjha** [comment]
I can't replicate this anymore.  I was seeing this this morning.  I'll close it for now and reopen if I can figure out how to recreate it.

**Comment by dylanjha** [comment]
Thanks for the quick response :+1:

**Comment by erickbelfy** [comment]
Hi guys, i grab this error again when i try to use `orderedlist` and also `unordered` list buttons using firefox

**Comment by milossh** [comment]
I get the same error now with latest firefox and medium-editor 4.12.12

**Comment by rishijain** [comment]
any particular use case when it occurs?

**Comment by j0k3r** [comment]
@milossh You don't need to comment every issue related to your problem. One is enough, we got notification, so don't worry.

Could you tell us more about that issue? Which line of the script is responsible for this error? Latest version of Firefox is 42?

**Comment by milossh** [comment]
Ok, sorry about that. Exact same line as in this issue. Yeah, firefox 42. NS_ERROR happens whenever I type in something, for every character.

**Comment by j0k3r** [comment]
I've just tried on my Mac with Firefox 42 and and the latest 4.12.x release and I didn't get the problem. Could you provide a jsfiddle that reproduce the issue? Thanks.

**Comment by blackboxmedia** [comment]
This Problem occurs when you try to format text inside a <p> -tag for example with an tag that actually is not allowed in the Code inbetween <p>.

Example:

```
<div contenteditable="true">
    <p>
        <b>lorem ipsum</b>
     </p>
</div>
```

Medium tries to make a <h1-6> -tag inside that <p> wich would not be compliant to w3c

```
<div contenteditable="true">
    <p>
        <h2>lorem ipsum</h2>
     </p>
</div>
```

**Comment by nmielnik** [comment]
@blackboxmedia thanks a ton for adding this info.  We've had this error come up via a bunch of different issues over the years.  Would you mind adding your repro steps to #1061 or as a separate issue if you don't feel #1061 is appropriate?  We would definitely appreciate it, thanks!
