### ISSUE TITLE
FEATURE REQUEST: .destroy()

### ISSUE THREAD

**Issue by comerc** [daviferreira/medium-editor#355]
Completely destroys the control and unbinds all event listeners so that it can be garbage collected.

.deactivate() does not quite fit

**Comment by daviferreira** [comment]
What is deactivate missing?

**Comment by nchase** [comment]
@comerc: `.deactivate()` removes event listeners, removes the nodes from the document, and deletes references. what is it missing?

**Comment by sisou** [comment]
Maybe he was put off by the name of the method. I would also think that `.deactivate()` merely makes the editor not react anymore, but keep its bindings. Thank god for the search function, I was about to ask the same thing ;)

**Comment by daviferreira** [comment]
Yeha, maybe we should change it to destroy or something :boom:

**Comment by nmielnik** [comment]
I agree, it is indeed misleading, but it is also one of our core and longest living method names and would likely break a lot of people if we changed it now.  I wonder if it is worth renaming?

**Comment by sisou** [comment]
Maybe it's enough to add an alias?

**Comment by nmielnik** [comment]
Opened #488 thoughts?
