### ISSUE TITLE
Control over pasted content

### ISSUE THREAD

**Issue by websirnik** [daviferreira/medium-editor#36]
When HTML is pasted you might want to have a control over which tags or attributes to ignore.

Use case: When a user pastes content that contains
```HTML 
<p style="font-size: 40px; color: purple; background: green;">
    Lorem Ipsum is <b>important</b>
</p>
```
I would obviously want to ignore `style` attribute, but to preserve `<b>`, so it would rendered according to my stylesheet.

Copy-pasting from another topic:  [Hallo.js](https://github.com/bergie/hallo) uses https://code.google.com/p/jquery-clean/ which is pretty powerful.

**Comment by michaelkoper** [comment]
+1 This would be very useful

**Comment by nmielnik** [comment]
This is now possible! Added in #518 and available in v4.3.0.

You can pass a set of tags and attributes that you would like removed on paste by using the `paste.cleanTags` and `paste.cleanAttrs` options passed during instantiation of MediumEditor.

You can also pass these options during manual HTML inserting when call the `pasteHTML` method.

**Comment by websirnik** [comment]
I'm testing 4.5.2. With the following options:
```js
paste: {
   cleanPastedHTML: true,
   forcePlainText: false
   }
```
any html that I paste gets rendered as a plain-text. I'm testing on the `clean-paste.html` from `/examples` folder.

Any example of how it should work exactly?

**Comment by nmielnik** [comment]
@websirnik 

So I'm seeing now how these option names are pretty confusing, but this is how it should work:

#### `cleanPastedHTML: false` + `forcePlainText: false`
If both options are false, we don't do any manipulating when pasting, everything gets passed into the editor.

#### `cleanPastedHTML: false` + `forcePlainText: true` (DEFAULT)
Whenever a user does a paste, we cancel the normal paste and extract the **plaintext** data from the user's clipboard (`event.clipboardData.getData('text/plain')`).  Once we have that, we'll replace any newlines with `<p>` tags, and escape any html entities and that's what will appear in the editor.

#### `cleanPastedHTML: true` + `forcePlainText: true` OR `cleanPastedHTML: true` + `forcePlainText: false`
When `cleanPastedHTML` is true, the `forcePlainText` option doesn't provide any change in functionality.
In this case, whenever a user does a paste, we cancel the normal paste and extract the **HTML** data from the user's clipboard (`event.clipboardData.getData('text/html')`)'.  Once we have that, we run this HTML through all of our filters and replacement code to clean up the HTML before it appears in the editor.

The one exception to this is for internet explorer.  For IE, we cannot get the HTML data from the clipboard, so pastes from IE always come through as plaintext.

Apologies for the confusion, does this answer your question?

**Comment by websirnik** [comment]
@nmielnik this is roughly what I understood. However the following settings, does not produce desired results: 
```js
paste: {
   cleanPastedHTML: true,
   forcePlainText: false
   }
```
When I paste `<a href="https://google.com">Google</a>`, I expect it would render as a hyperlink [Google](https://google.com), but it renders as a plain-text `Google` (not link). 

Can you check this behaviour. I'm testing on the` /demo/clean-paste.html` that's included in the repo.

**Comment by nmielnik** [comment]
where are you copying the text from, and what browser are you using?

**Comment by websirnik** [comment]
I'm testing on Safari/ChromeCanary. I must say after further testing I got some content pasted correctly. But if you take for instance this [link](http://techcrunch.com/2015/04/15/sources-yahoo-in-talks-to-buy-foursquare/), and copy-paste the 1st paragraph from the article, links does not preserve.

**Comment by nmielnik** [comment]
@websirnik can you pull down the branch I made `paste-fixes` and see if this fixes your issue?  I made some fixes that might help with this.

**Comment by nmielnik** [comment]
I've opened #563 to track this, let's continue the conversation there.
