### ISSUE TITLE
module was used before it was defined

### ISSUE THREAD

**Issue by CharlGottschalk** [daviferreira/medium-editor#366]
My build keeps failing with the following errors.

`'module' was used before it was defined`
`'define' was used before it was defined`

Any idea why this is happening?

**Comment by nmielnik** [comment]
This is likely because of jslint, in which case you'll want to add `module` and `define` to the list of global methods to be ignored at the (top of the file)[https://github.com/daviferreira/medium-editor/blob/master/src/js/medium-editor.js#L1].

**Comment by CharlGottschalk** [comment]
Thanks for the response...once I synced the fork upstream the build passed.
