### ISSUE TITLE
does not match the actual medium editor

### ISSUE THREAD

**Issue by timothyerwin** [daviferreira/medium-editor#372]
![screen shot 2015-01-20 at 12 52 27 pm](https://cloud.githubusercontent.com/assets/2653209/5822570/482c9a44-a0a3-11e4-8685-8443ace8e9ac.png)

The medium editor looks like the screen shot above. I think at the basic this control should identically mimic the medium editor.

+ Justify center is not included in the basic toolbar here, and also the justify center when untoggled on medium will go back to left.

+ Another bug is that sometimes the toolbar shows up without any highlighting of text

+ If you have default text in the medium editor say, `<h3>hello</h3` it will be set to `display:none` by this editor.

+ Also by default medium has h1, h2, and h3.

+ If you highlight h1 and click bold it actually makes it unbold

![screen shot 2015-01-20 at 1 02 07 pm](https://cloud.githubusercontent.com/assets/2653209/5822752/98f83964-a0a4-11e4-8f4a-10475f06c8c8.png)

**Comment by daviferreira** [comment]
You can set the options as you like, so the editor can look like medium's.

About the bugs, could you please open a different issue for each of them, with more details on how to reproduce them? 

Cheers!
