### ISSUE TITLE
Add bower installation to README

### ISSUE THREAD

**Issue by brunomperes** [daviferreira/medium-editor#379]
It would be great if we could install it using `bower install medium-editor`

**Comment by hacfi** [comment]
@brunomperes That should already work!?

**Comment by brunomperes** [comment]
Yes! I just tried and it worked, maybe adding to the README for new users?

**Comment by hacfi** [comment]
Good idea, yes!

**Comment by daviferreira** [comment]
@brunomperes how about a pull request? :smile:
