### ISSUE TITLE
React port

### ISSUE THREAD

**Issue by joaomilho** [daviferreira/medium-editor#383]
Any plan to port it to React?

**Comment by nmielnik** [comment]
So `contenteditable` elements are particularly problematic and troublesome in react since it's a browser managed DOM manipulation that react does not have control over.  Thing can be hairy if you try to allow react to manage the `contenteditable` element itself and we were unable to find anywhere where people had examples of good working cases.

We have a working react component but we don't attach any events to the editable element itself.  We take in defaultContent as a prop, and only update our state when the toolbar is hidden by medium-editor (attaching `.onHideToolbar` method to the medium-editor instance, which is a good indicator that the user has click outside of the component so we can change the underlying HTML and save our state).  This is a paraphrase of code that we have working so I apologize if it doesn't work completely copy and pasted:

```javascript
var MediumEditorComponent = React.createClass({
    getInitialState: function() {
        return {
            content: this.props.defaultContent
       };
    },

    createMediumConfig: function {
        // build and return your medium config properties
    },

    componentDidMount: function() {
        this.medium = new MediumEditor(this.getDOMNode(), this.createMediumConfig());
        this.medium.onHideToolbar = function() {
            this.setState({ content: this.getDOMNode().innerHTML });
        }.bind(this);
    },

   componentDidUpdate: function() {
       this.medium.deactivate();
       this.medium.init(this.getDOMNode(), this.createMediumConfig());
   },
   
   componentWillUnmount: function() {
       this.medium.deactivate();
   },

   render: function() {
       return (
           <div
               contentEditable="true"
               dangerouslySetInnerHTML={{__html:this.props.content}}
           >
	   </div>
        );
    }
}
```

Also note that currently medium-editor injects the toolbar and anchorForm (for adding/editing anchor tags) into the DOM, which is another aspect that is not React managed nor super React friendly.

**Comment by joaomilho** [comment]
Awesome explanation, @nmielnik . As far as ```contenteditable``` goes I can see why react doesn't help much, but on the toolbar it seems to me manageable. I'll try the component and let u know.

**Comment by dfguo** [comment]
I think using onBlur is a better way to tell if the user has clicked outside the component

**Comment by nmielnik** [comment]
The problem with blur is that it fires when you click into the toolbar for medium-editor.  Especially in the case where you are adding/editing a link, where a textbox and checkboxes are displayed inside the toolbar which steals focus completely away from the contenteditable.

medium-editor has a few events handlers for detecting when the focus is no longer within the contenteditable or the toolbar, including using capture on the document to listen to all `focus` and `click` events.

**Comment by dfguo** [comment]
I see. The only issue with using ```onHideToolbar``` is when the user decided to just edit the text without selecting the text, the toolbar will never show up, and thus ```onHideToolbar``` will not be invoked.

**Comment by nmielnik** [comment]
This is a good point, as I was thinking only of the use case of using the `staticToolbar` and `updateOnEmptySelection` options, which are what I'm using in my react case.

We have added custom events into medium-editor, so it would definitely be possible to expose a custom `blur` event.  We'd have to tinker with the logic and start maintaining when a specific element has focus (including inside the toolbar or anchor preview) but it seems do able.

**Comment by nmielnik** [comment]
@dfguo I have a PR that exposes custom focus and blur events that I will be leveraging in our react component.  I'm hoping this will be a much better alternative to `onHideToolbar` and `onShowToolbar` as you mentioned before.

**Comment by dfguo** [comment]
awesome! thanks for the update!

**Comment by nmielnik** [comment]
For those who are looking for a hook for saving the state of the contenteditable, you can use `blur` now:

```js
// Assuming your using dangerouslySetInnerHTML to set the contents from the component's state
var editor = new MediumEditor('.editor');
editor.subscribe('blur', function (event) {
    // save the contents of the editor in state
});
```

This blur event only fires when the editor is clicked outside of (not when clicking on things like toolbar buttons, anchor-preview, etc.)

**Comment by dfguo** [comment]
good stuff! thanks!

**Comment by gianmarcotoso** [comment]
I've noticed that when the editor is hidden/destroyed, a subsequent call to .setup() doesn't reinitialize it properly: the attributes are not placed back on the editor's div and the events are not fired anymore. 

I'm using React 0.13.3 w/ Browserify.

**Comment by j0k3r** [comment]
@gianmarcotoso and which version of MediumEditor are you using? On which browser did you get this behavior? Could you provide a jsfiddle to reproduce the bug? Thanks.

**Comment by gianmarcotoso** [comment]
I'm using version 5.7.0. Actually, I managed to make it work ([fiddle](http://jsfiddle.net/e8pfefkz/1/)) but I have to manually rebind events after destroying and re-initing the editor. Doing destroy+setup doesn't work, as both events and attributes are lost (just replace the init+subscribe calls with a setup call in the `componentDidUpdate` method in the fiddle).

**Comment by jatwork** [comment]
Found a [react-medium-editor](https://github.com/wangzuo/react-medium-editor) and it looks promising.

**Comment by nmielnik** [comment]
Thanks for updating this issue @jatwork , we had called out the react port in the [documentation](https://github.com/yabwe/medium-editor/wiki/Wrappers-and-Integration) but forgot to open the issue.

Thanks a ton to @wangzuo for the react-port!
