### ISSUE TITLE
Impossible to use on table-based layouts (ex. HTML newsletters)

### ISSUE THREAD

**Issue by hellocosmin** [daviferreira/medium-editor#390]
Even the most basic table-based layout confuses the script.

Please see this Fiddle, created with an email template from ZURB (http://zurb.com/playground/projects/responsive-email-templates/newsletter.html) :

http://jsfiddle.net/ongk3utq/3/

As you can see, only the first line of text shows the editor toolbar. Anything else you try to edit, the toolbar shows for a brief moment and then gets hidden. Using the latest version of Medium Editor, just downloaded before writing this. Tested in Chrome, Firefox, IE.

Things noted / other thoughts:
- sub/superscript won't work in Chrome if you have a more complex table-based HTML layout (it applies the formatting, but is then unable to remove it). I doesn't matter if the parent element is a block or inline level element.
- removing `this.toolbar.classList.remove('medium-editor-toolbar-active');` from line 1477 makes it always show up correctly, but I suspect this can lead to toolbar position issues on de/activate() ?
- is the issue above influenced perhaps by the defined parentElements in the init function? (there's no parent 'td' defined in there)

@daviferreira - I kindly ask that you take a look, I will appreciate any advice. Thank you :)

**Comment by daviferreira** [comment]
Actually it is not a but with the table element, but with multiple elements with the same class (tried with various p.editable). If you put the 'editable' class on your table only, instead of each p, it should work. 

Anyways, I will take a look.

**Comment by hellocosmin** [comment]
Thanks for the explanation Davi.

Problem is, one might not want to make an entire table contenteditable. In such cases, one would need to enable Medium Editor on specific elements only, so as to not allow a user to edit everything in that table and break it or even completely delete it.

**Comment by daviferreira** [comment]
Should be fixed now, latest version :+1:

**Comment by hellocosmin** [comment]
Indeed it is, works perfectly. 

The only remaining issue is the sub/superscript in Webkit: even with the latest fix, once you apply it you can't click again to remove it. Fails even when selecting a few letters inside a word, so the only option a user is left with is to Ctrl/Cmd+Z.

Thanks so much Davi, loving Medium Editor so far :)
