### ISSUE TITLE
input event not firing in IE10 or IE11?

### ISSUE THREAD

**Issue by pascalpp** [daviferreira/medium-editor#394]
For me, the `input`is not firing on mediumedtior in IE11.

According to this: https://connect.microsoft.com/IE/feedback/details/794285/ie10-11-input-event-does-not-fire-on-div-with-contenteditable-set, the input event doesn't fire on any contenteditables (not just mediumeditor) in IE10 or IE11:

I've confirmed this in my IE11 VM using the fiddle mentioned on the above page: http://jsfiddle.net/7VQxd/ 

But the ReadMe for this project says that the `input` event should work in IE9+. Anyone else having this issue?

**Comment by pascalpp** [comment]
It appears that the input event is supported on text inputs and textareas in IE9+, but not contenteditables. I ended up using this snippet from http://stackoverflow.com/questions/1391278/contenteditable-change-events:

```
$('body').on('focus', '[contenteditable]', function() {
    var $this = $(this);
    $this.data('before', $this.html());
    return $this;
}).on('blur keyup paste input', '[contenteditable]', function() {
    var $this = $(this);
    if ($this.data('before') !== $this.html()) {
        $this.data('before', $this.html());
        $this.trigger('change');
    }
    return $this;
});
```

which fires a change event on the contenteditable element. Then I just listen for that change event.

**Comment by nikhilsreeni** [comment]
> It appears that the input event is supported on text inputs and textareas in IE9+, but not contenteditables. I ended up using this snippet from http://stackoverflow.com/questions/1391278/contenteditable-change-events:
> 
> ```
> $('body').on('focus', '[contenteditable]', function() {
>     var $this = $(this);
>     $this.data('before', $this.html());
>     return $this;
> }).on('blur keyup paste input', '[contenteditable]', function() {
>     var $this = $(this);
>     if ($this.data('before') !== $this.html()) {
>         $this.data('before', $this.html());
>         $this.trigger('change');
>     }
>     return $this;
> });
> ```
> 
> which fires a change event on the contenteditable element. Then I just listen for that change event.

work for me
