### ISSUE TITLE
Use constants for key codes to improve readability

### ISSUE THREAD

**Issue by robinwassen** [daviferreira/medium-editor#398]
I would suggest to use named constants instead of using the raw number when checking key codes, for example:

```javascript          
if (e.which === 32) {
    node = getSelectionStart.call(self);
    .....
```

Would be easier to read if it was:

```javascript
if (e.which === KeyCode.ENTER) {
    node = getSelectionStart.call(self);
    .....
```

I can contribute with a pull request if you think this is a good idea.

**Comment by nmielnik** [comment]
This has been on my to do list for a while, I think it's a great idea.
