### ISSUE TITLE
Keyboard shortcuts support

### ISSUE THREAD

**Issue by websirnik** [daviferreira/medium-editor#40]
* Bold - Cmd+B
* Italic - Cmd+I
* Underline - Cmd+U

**Comment by j0k3r** [comment]
+1

This is working on Chrome, because I guess Chome know that you are inside a `contentEditable` node, so it handles keyboard shortcut properly. But it doesn't work on Firefox.

Any clues about that?
Should we use an external lib to handle shortcuts?

**Comment by R0cker** [comment]
It doesn't work in Safari either. Any clues?
