### ISSUE TITLE
Add ME to cdnjs?

### ISSUE THREAD

**Issue by hellocosmin** [daviferreira/medium-editor#403]
Would be useful, especially when testing with JSFiddle.

**Comment by daviferreira** [comment]
From their docs, seems like a very complicated process :fearful:

Be my guest if you want to submit it, anyone can do it I think :smiling_imp:

**Comment by hellocosmin** [comment]
Yeah, seems it is. And since I'm only starting out with Github, I'll need to learn some more. Thanks anyway though, keep up the great work :+1:
