### ISSUE TITLE
Toolbar not going away at the end of words

### ISSUE THREAD

**Issue by daviferreira** [daviferreira/medium-editor#417]
![meditor mp4](https://cloud.githubusercontent.com/assets/38787/6136068/16b5acea-b16e-11e4-87ac-ad74d72ff504.gif)

**Comment by daviferreira** [comment]
Also occurs when you place the cursor right after any word.

**Comment by daviferreira** [comment]
Fixed by 0208ca3

**Comment by nmielnik** [comment]
Exploring alternative way to solve this issue....

**Comment by nmielnik** [comment]
Fixed by 6ad50a4
