### ISSUE TITLE
User-centered labels on toolbar

### ISSUE THREAD

**Issue by uimanwashere** [daviferreira/medium-editor#419]
I know this is a clone of Medium Editor, but talking about UX it would be a great improvemnts if you could offer more friendly labels on toolbar buttons.

# How?

> What it says: b, i, h2, h3
> Should say: strong, italic, firstHeading, secondHeading

# Why?

Well, users don't need to know what a H2 or H3 is.

**Comment by uimanwashere** [comment]
Sorry about that, just found the buttonLabels. My bad U_U

**Comment by daviferreira** [comment]
No worries, our docs suck :)
