### ISSUE TITLE
Consider developing medium-editor as a plugin / toolbar package for Scribe

### ISSUE THREAD

**Issue by miztroh** [daviferreira/medium-editor#420]
There's some great work going on over at https://github.com/guardian/scribe.  Scribe is toolbar-agnostic and all of its functionality comes from plugins.  You might save time by developing the Medium.com experience as a Scribe plugin / toolbar package instead of duplicating efforts on the underlying mechanics.

**Comment by daviferreira** [comment]
Yeap, definitely something we have in mind, not only for Scribe, but other editor out there. Thanks for the feedback! :beers:
