### ISSUE TITLE
All mouseup events blocked from propagating to window.document

### ISSUE THREAD

**Issue by brianreavis** [daviferreira/medium-editor#421]
https://github.com/daviferreira/medium-editor/blob/master/src/js/medium-editor.js#L1203

This breaks other components' behavior – one example being [leaflet](http://leafletjs.com/). When you mousedown to drag a map, and then go to mouseup to stop dragging... it's locked in the "dragging" state because medium-editor blocks the event from ever getting to the document ([relevant handler](https://github.com/Leaflet/Leaflet/blob/v0.7.3/dist/leaflet-src.js#L7594)).

What is the best approach to fix this? Thanks for the excellent work on the library :)

**Comment by daviferreira** [comment]
@brianreavis could you test against the latest code on master please?

**Comment by brianreavis** [comment]
@daviferreira Sorry for the slowness in getting to this. Yep, it's fixed in the current release. Thanks!
