### ISSUE TITLE
AngularJS + jQuery results in placeholder being visible on page load

### ISSUE THREAD

**Issue by etcook** [daviferreira/medium-editor#426]
I've been developing an Angular app, and recently needed to go ahead and enqueue jQuery for a lib I was using. When I did that, medium-editor started showing the placeholder by default. Once you click on any of the editable elements, the placeholders all disappear on the page.

Do you have any suggestions rather than "cleansing" the dom of that class to remedy? Or better yet, an idea of what might be causing it?

**Comment by daviferreira** [comment]
Can you provide a fiddle or a url? Tried to reproduce it with angular and jquery on the demo page, but no luck.

**Comment by etcook** [comment]
Do you mind providing your email address? I'll send it "offline" thanks!

**Comment by daviferreira** [comment]
hi@daviferreira.com

**Comment by etcook** [comment]
@daviferreira Was this addressed?

**Comment by daviferreira** [comment]
@etcook sorry, should be yea :)
