### ISSUE TITLE
Toolbar not showing when selecting from beginning of text

### ISSUE THREAD

**Issue by steoo** [daviferreira/medium-editor#430]
I'm having this issue when updated medium-editor from 1.9.13 to latest review. 
When the selection end to the beginning of the text the toolbar hides itself.

![issue](https://cloud.githubusercontent.com/assets/3333573/6216841/f459871c-b60d-11e4-8528-5bc9955a3383.gif)

**Comment by daviferreira** [comment]
The problem is the mouseup event is being triggered outside the editor area, and we are not listening to that currently. We should fix that by adding yet another event listener to document.body :imp:

**Comment by steoo** [comment]
I would like to contribute, the problem is that I did not have time to give a look to the entire code. I guess I have to spend some time to :)

**Comment by steoo** [comment]
I developed an Hack, I don't know if it can work neither tested it with a unit test, so I won't  create a branch for this, I feel insecure eheh. Anyway :

`````
blurFunction = function (e) {
      var isDescendantOfEditorElements = false,
            sel = meSelection.getSelectedParentElement(window.getSelection().getRangeAt(0)), //added this variable
            i;
                                   
           for (i = 0; i < self.elements.length; i += 1) {
              if (mediumEditorUtil.isDescendant(self.elements[i], e.target)
                  || mediumEditorUtil.isDescendant(self.elements[i], sel)) { //added this control
                  isDescendantOfEditorElements = true;
                  break;
               }
            }

`````

**Comment by daviferreira** [comment]
@steoo Don't feel insecure, man, we are nice people, we will help you if needed. But it looks good to me, please submit a Pull Request :)

I can help you out about writing a test, don't worry about that. And not everything should be tested :smile:

**Comment by steoo** [comment]
@daviferreira I did not want to commit also util.js, I made a mistake ehm. I'm gonna fix this immediatly

**Comment by daviferreira** [comment]
Don't worry about it :)
