### ISSUE TITLE
Move to JSHint for 'linting'

### ISSUE THREAD

**Issue by nchase** [daviferreira/medium-editor#437]
Reasons to move to JSHint:
* JSHint provides a number of improvements and additional options that JSLint doesn't have.
* The JSHint grunt task [`grunt-contrib-jshint`](https://github.com/gruntjs/grunt-contrib-jshint) is a community standard (~33K downloads per day according to NPM), with a much larger support network than our current [`grunt-jslint`](https://github.com/stephenmathieson/grunt-jslint)
* "ignore" directives can be supplied broadly and/or more finely (e.g. JSHint supports a `.jshintignore` file where you can specify files/blobs to ignore
* JSHint continues to move and is updated regularly with improvements, JSLint is (seemingly) really only maintained by Crockford.

**Comment by daviferreira** [comment]
:+1:

**Comment by xaddict** [comment]
:+1:

**Comment by daviferreira** [comment]
cad8f45872e85b74df7af6d595b567613382a5d9
