### ISSUE TITLE
Can't turn off superscript

### ISSUE THREAD

**Issue by Nesvet** [daviferreira/medium-editor#448]
For some reason, I can't remove the superscript formatting. It turns on for selection once and forever.

P. S. Thank you for this awesome stuff.

**Comment by nmielnik** [comment]
What version of medium-editor are you using and what browser are you seeing this in?  Would you be able to go into more details about the situation where this is happening, or create a [jsfiddle](http://jsfiddle.net/)?

**Comment by hellocosmin** [comment]
Happens to me as well, in Chrome only, ME 2.4.6. I suppose it's Webkit-related.

In my case, the editable is a paragraph that is a direct descendant of a td (it's a table layout, a newsletter). Weird thing is that I tried a fiddle with a simple table and it [works fine](http://jsfiddle.net/gfqzr2gd/5/).

I'm thinking it may have to do with the nesting in my table-based layout, though not sure why that would happen since the editable is a block level element (I even tried having a div or heading instead of a paragraph). Also, my entire table layout is inside a fixed-positioned div, if that matters.

I'll continue testing to find a way to reproduce that in a fiddle.

**Comment by nmielnik** [comment]
2 things to potentially look at to see what could be causing this:

1) If you have a case where this is reproducing, try using `queryCommandState()` to see whether Chrome thinks the node is superscript or not.  You can do this by selecting the node manually and running the command, or selecting the element programmatically 
```javascript
// Assuming element is the DOM Element that is current superscript
var range = document.createRange(),
    sel = window.getSelection();

range.selectNodeContents(element);

console.log(document.queryCommandState("superscript"));
```
The result of the call to `document.queryCommandState("superscript")` should return a boolean specifying whether the current selection is superscript or not.  If it returns false, it may be an indicator that some css may be causing Chrome to think that the element isn't actually superscript, which would explain why you're not able to turn it off.

2) From what I was able to find, it seems like the CSS equivalent of a `<sub>` node would be:
```css
sup { 
    vertical-align: super;
    font-size: smaller;
}
```
So, perhaps look to see if the superscript node is having alternate values for these css properties set or inherited, which could cause the browser to behave inconsistently when attempting to turn superscript 'off'

**Comment by hellocosmin** [comment]
@nmielnik thanks for the insights.

Tested with your advice and in Chrome, as I expected, I get:

- false when checking with queryCommandState
- 'baseline' vertical-align
- correct font-size

In Firefox, same results, but 'true' for the queryCommandState.
Double checked to make sure I was grabbing the correct element and that's correct, I'm using :

<pre>if (sel.rangeCount > 0)
    		var element = sel.getRangeAt(0).startContainer.parentNode;</pre>

**Comment by dweebit** [comment]
We had the some problem in chrome. Adding the following to our css fixes it. Thanks @nmielnik! 
```css
sup {
  vertical-align: super;
}

sub {
  vertical-align: sub;
}
```

**Comment by daviferreira** [comment]
Should we add this to the default css maybe?

**Comment by hellocosmin** [comment]
That CSS works for me too, thanks @nmielnik :)

@daviferreira yes, I think it should be there.

**Comment by nmielnik** [comment]
Opened pull request #487 

@dweebit @hellocosmin can you verify that this is sufficient?

**Comment by hellocosmin** [comment]
Yes, confirmed to work perfectly fine in Chrome now, too. Thank you sir!

**Comment by nmielnik** [comment]
np, pretty easy thanks to you pin pointing the issue :sunglasses:

**Comment by nmielnik** [comment]
@olgagr added some [sample button overrides](https://github.com/yabwe/medium-editor/issues/724#issuecomment-120415261) that leverage `styleWithCSS` to handle subscript and superscript, as an alternate way to work around this issue.
