### ISSUE TITLE
Semantic Versioning?

### ISSUE THREAD

**Issue by orthes** [daviferreira/medium-editor#459]
Since my [plugin](https://github.com/orthes/medium-editor-insert-plugin) depends on the editor, I'd like to ask what versioning process do you use? Have you considered using [Semantic Versioning](http://semver.org/)?

Update from 2.4.2 to 2.4.3 introduced full content actions which should be a minor change, not only patch according to semver.

Also is jump from 2.4.6 to 3.0.0 backwards incompatible, that's why there is a major version change?

One last question: why there is a sudden update from 3.0.0 to 3.0.7 without versions in between?

I'm asking this questions so I can properly set up MediumEditor version in my plugin dependencies. Can I use ^3.0.0 and be sure that all minor changes will be compatible?

**Comment by daviferreira** [comment]
Yeah, we need to sort this out, my bad :+1: 

But thanks for bringing the discussion up
