### ISSUE TITLE
Errors on RequireJS call

### ISSUE THREAD

**Issue by xaddict** [daviferreira/medium-editor#464]
When using RequireJS to load in medium-editor on some pages via:
```
requirejs(['medium-editor'],function(MediumEditor){
  MediumEditor('.editable');
});
```

it returns ```Uncaught TypeError: Cannot read property 'init' of undefined``` from this line in the code:
```
function MediumEditor(elements, options) {
    'use strict';
    return this.init(elements, options);
}
```
---
When loading it standalone (but alongside RequireJS) via
```
<script src="js/medium-editor.js"></script>
<script>var editor = new MediumEditor('.editable');</script>
```
it returns:
```
Uncaught ReferenceError: MediumEditor is not defined
require.js:8 Uncaught Error: Mismatched anonymous define() module: function () {
	return factory;
}
```

**Comment by orthes** [comment]
What version do you use? This should be fixed in version [3.0.7](https://github.com/daviferreira/medium-editor/releases/tag/3.0.7) - released yesterday.

**Comment by xaddict** [comment]
RequireJS ```2.1.16```
Medium-Editor ```3.0.7```
There's no version number in the file but I redownloaded via your version link.
Before that I downloaded the master (today) via 'Download Zip'

Should I put it inside requirejs.config, and if so, how?
---
```
requirejs(['medium-editor'],function(MediumEditor){
  MediumEditor('.editable');
});
```
still returns ```Uncaught TypeError: Cannot read property 'init' of undefined```

**Comment by orthes** [comment]
You need to use ```new``` keyword in order to make a new object: ```new MediumEditor('.editable');```. MediumEditor is only an object prototype.

**Comment by xaddict** [comment]
Ahh thank you :+1:

And how would I add it to the requirejs config?

**Comment by orthes** [comment]
Simply add it to paths:

```
require.config({
    paths: {
        'medium-editor': '../bower_components/medium-editor/dist/js/medium-editor.min'
    }
});
```

And then use it like this:

```
define([
    'medium-editor',
], function (MediumEditor) {
    var editor = new MediumEditor('.editable');
});
```

**Comment by xaddict** [comment]
Thanks :+1: 

I just started using it today, but it looks amazing. I'll try to contribute
