### ISSUE TITLE
Missing Argument in getSelectedParentElement()

### ISSUE THREAD

**Issue by michael-gruber** [daviferreira/medium-editor#470]
Hello,

while developing an extension, i just came across a problem:

getSelectedParentElement: function () {
    return Selection.getSelectedParentElement();
},

The range argument is missing, should be the following, right?

getSelectedParentElement: function (range) {
    return Selection.getSelectedParentElement(range);
},

Thanks
Michael

**Comment by nmielnik** [comment]
Yes, that looks like a problem.  Perhaps the range argument should be optional, and if it's not passed we should call default it to `window.getSelection().getRangeAt(0)` before calling into `Selection.getSelectedParentElement()`?

Would you like to open a pull request?

**Comment by daviferreira** [comment]
@michael-gruber what extension is that? :smile:

**Comment by michael-gruber** [comment]
I am working on a CMS based on the Laravel Framework. For content-editing i am using medium-editor (which i love!). Furthermore i am using the Foundation Framework and for creating links, i wrote an extension which opens an overlay.
So it's very specific to my project.
![bildschirmfoto 2015-03-03 um 21 53 30](https://cloud.githubusercontent.com/assets/3738971/6472051/db3f8cf2-c1ef-11e4-9a48-2319b9b89f72.png)
![bildschirmfoto 2015-03-03 um 21 53 37](https://cloud.githubusercontent.com/assets/3738971/6472055/e6e96c8a-c1ef-11e4-9ab8-72f0b2a10b00.png)

**Comment by daviferreira** [comment]
It looks awesome, maybe one day you release the extension as an open source project? If you do it, let us know :smile:
