### ISSUE TITLE
Text Formatting

### ISSUE THREAD

**Issue by steoo** [daviferreira/medium-editor#476]
It would be awesome if you could try to create a system to unify taggings of text cross-browsers and translate it in ranges. This is an awesome advantage when saving the content that has been edited. Currently browsers natural behaviour on text formatting breaks a lot of tags and is different between them. 
Quoting https://medium.com/medium-eng/why-contenteditable-is-terrible-122d8a40e480
> *markups, a list of formatting text ranges, like “bold from char 1 to 5”*

**Comment by daviferreira** [comment]
Yes, contenteditable is terrible :)

Keeping #434
