### ISSUE TITLE
Bug when removing first item in a list

### ISSUE THREAD

**Issue by mphasize** [daviferreira/medium-editor#479]
Hej, I just stumbled upon this weird little bug: When I remove the first item in a list, an unwanted `div` element is created before the list.

Steps to reproduce:
In an empty editor, write a little bit of text. Select the text and turn it into an unordered list (so that nothing is on top of that list). Now assume that you want to add something before that list. Since you cannot navigate there, one possibility is to hit *enter* when the cursor is in the first list item before the text – this will create an empty list item on the top. Then hit *backspace* on that empty list item. The cursor indentation is returned to normal and we can now write on top of the list. **However**, when checking the DOM, we see that we're now writing inside a `div` element that got silently created and shouldn't really be there.

P.S.: Thanks for the great work on the editor!

**Comment by nmielnik** [comment]
So this looks like something that the browser is doing on its own.  I tried the steps you mentioned in a few different browsers, and I saw the following:

*Chrome*
A `<div><br/></div>` gets inserted before the `<ul>`

*Firefox*
A `<br/>` gets inserted before the `<ul>`

*IE11*
A `<p></p>` gets inserted before the `<ul>`

If we wanted to fix this, we would need to add some logic to detect when this is happening and try to standardize the HTML.  If you find a way to fix this, please share the code or open a pull request.

Besides the obvious issue with a stray element getting inserted, are there other issues this causes?  It seems like you can always delete that element and add new text, is that not the case?

**Comment by mphasize** [comment]
Yes, different browsers handle `contenteditable` differently. As far as I have seen, other libraries with a similar purpose (like [Medium.js](https://github.com/jakiestfu/Medium.js)) try to normalize the behavior between different browsers. I thought that would be the same case here.

My problem actually occurs further downstream, as I'm also using the MeMarkdown plugin which converts the stray element into inline HTML in the Markdown block. (Which may actually have a use case, but is not helpful for my app). A mindful editor may notice the problem and fix it, but my average user will probably not even notice the problem.

> It seems like you can always delete that element and add new text, is that not the case?

Would there be an easy way to do this programmatically, maybe based on some events emitted by medium-editor? If this has to be done by the user, it's definitely an issue. ;-)

**Comment by nmielnik** [comment]
Yes, I definitely agree that this would be the job of medium-editor to fix, I wanted to clarify the severity of the issue and to make sure I understood all the side effects. I definitely was not trying to be dismissive.

I have added this issue to our internal backlog, and hopefully either a user or one of us can get to it in a reasonable amount of time. We will update this issue whenever that happens.

**Comment by mphasize** [comment]
@nmielnik No worries, I didn't perceive your answer as dismissive. 

> If we wanted to fix this, we would need to add some logic to detect when this is happening and try to standardize the HTML.

When I read this, I started wondering if medium-editor is doing any normalizing – because otherwise I thought that the issue I found would simply be an extension of that. If you could point me to a good starting point in the code, I will look if I can think of a solution. Thanks

**Comment by nmielnik** [comment]
So there is some html cleanup code in place, an example that was added would be [here](https://github.com/daviferreira/medium-editor/blob/master/src/js/core.js#L50) where the `handleBlockDeleteKeydowns()` method handles whenever the user hits `Delete`, `Backspace`, or `Enter` while in various positions relative to a `<header>` tag.

My guess its you could add another handler attached to the `editableKeyDelete` custom event, via the `subscribe()` method.  This event fires whenever the keydown event fires for `Delete` or `Backspace` on any of the elements that medium-editor is monitoring.  If you need some other events, you can add another custom event in `events.js`, or just attach a DOM event handler via the `.on()` method.

Hope that helps, and thanks for looking into it!

**Comment by mphasize** [comment]
So I updated to the latest `master` and had a look at the functions. However, while doing this, I noticed something else:

- when I convert text (in a `p`) into a list item, the `ul` is created inside the `p` although I would expect it to replace the `p` element

This might be a reason for the problem above.

**Comment by mphasize** [comment]
Aha, there's also an open bug for Chrome https://code.google.com/p/chromium/issues/detail?id=297211
