### ISSUE TITLE
toolbar flashing with multiple instances of medium-editor on page

### ISSUE THREAD

**Issue by nmielnik** [daviferreira/medium-editor#486]
When multiple instances of medium-editor exist on the page, various toolbars appear and disappear quickly when clicking in areas of the page that are outside of the contenteditable sections.  This can be seen here by clicking on the far left edge of the page multiple times.

http://daviferreira.github.io/medium-editor/static-toolbar.html

**Comment by daviferreira** [comment]
Sick FX :zap:
