### ISSUE TITLE
Javascript crashes with compiler error when used in Meteor

### ISSUE THREAD

**Issue by blakeelias** [daviferreira/medium-editor#490]
Error message below:

=> Errors prevented startup:

While Building the application:
bower_components/medium-editor/src/wrappers/end.js:2:5: Unexpected token )
bower_components/medium-editor/src/wrappers/start.js:16:3: Unexpected end of input

=> Your application has errors. Waiting for file change.

**Comment by daviferreira** [comment]
I don't really know how Meteor works, but I don't think you should be using the /src dir, just use files on the /dist folder:

```
"main": ["dist/js/medium-editor.js",
           "dist/css/medium-editor.css",
           "dist/css/themes/default.css"]
```
