### ISSUE TITLE
Expose custom event for when content changes (ie `onInput`)

### ISSUE THREAD

**Issue by nmielnik** [daviferreira/medium-editor#493]
Rather than recommending that users attach to the `onInput` event of the contentedtiable element itself, it seems like it would make sense for us to expose a way to attach to it.

This is especially true now that we have custom events exposed.

This could address several issues as well, starting with #142

**Comment by nmielnik** [comment]
Added in #553

**Comment by nmielnik** [comment]
The 'input' event currently is not fired on `contenteditable` elements in any version of IE, so we need to find a workaround for IE9+.

IE11 has MutationObserver which works for us, but this is new in IE11.

Because of this issue, we don't fully support the `<textarea>` solution we've implemented, since it relies on the `input` event to synchronize input in the `contenteditable` with the content of the `<textarea>`

**Comment by daviferreira** [comment]
How about this by our beloved Tim Down http://stackoverflow.com/a/17763884

**Comment by nmielnik** [comment]
This now exists (as of #597 and v 4.8.0) via the `contentEditable` custom event.
