### ISSUE TITLE
Image size

### ISSUE THREAD

**Issue by oxhey** [daviferreira/medium-editor#497]
When I drag and image into an editable section , the size is massive. Is there was way to set it to a default size or allow the image to be resized?

**Comment by daviferreira** [comment]
Applying a ```max-width``` to img tags does not help you?

**Comment by oxhey** [comment]
Whoops , forgot basic css .  What about image resizing . is that a feature that will be implemented?

**Comment by daviferreira** [comment]
I think that is way out of our scope, but we could add the max-width rule to our base css :)
