### ISSUE TITLE
Mediumeditor is setting a global property named "self"

### ISSUE THREAD

**Issue by steoo** [daviferreira/medium-editor#504]
I noticed that the script is setting a property "self" at: https://github.com/daviferreira/medium-editor/blob/a5b7a58f59c018c16723890749e178997b4d6a02/src/js/polyfills.js#L180 .
In my modest opinion `self` is almost a *keyword* (everyone uses it in local scopes), so if you accidentally forget to declare as local `var` you'll end up in `.call` with `window` as context. Maybe I'm wrong, but I am experiencing this situation right now

**Comment by phiggins42** [comment]
that isn't setting the property, it's passing the reference of that property to the IIFE ... `self` is a thing already: https://developer.mozilla.org/en-US/docs/Web/API/Window/self ... I don't believe this is "leaking" this global.

**Comment by steoo** [comment]
Ok, my fault, didn't know that :) thank you very much
Il 28/mar/2015 23:34 "Peter E Higgins" <notifications@github.com> ha
scritto:
