### ISSUE TITLE
Toolbar disappears on click in Safari

### ISSUE THREAD

**Issue by tezzataz** [daviferreira/medium-editor#507]
Hi guys,

Just updated to the latest version of this and it doesn't work in Safari. Everything works fine up until you click a button, the toolbar then disappears completely and nothing happens. Tested in all other browsers and it works perfectly.

Thought it might be my app but tried the demo from the source files and the same problem occurs.

For reference I am using Safari Version 8.0.5 (10600.5.15). There are no errors or alerts either.

**Comment by nmielnik** [comment]
Yeah, this is definitely issue, we're looking into it.

**Comment by nmielnik** [comment]
In the meantime, please use v4.0.0, the issue shouldn't exist in that version

**Comment by tezzataz** [comment]
Perfect, yeah 4.0.0 works fine, thanks.

**Comment by patrick-webs** [comment]
https://github.com/daviferreira/medium-editor/pull/509 should fix this

**Comment by nmielnik** [comment]
@tezzataz Thanks a ton for finding this.
We have fixed this, and the fix in part of the v4.0.2 release

**Comment by tezzataz** [comment]
Perfect guys, thanks.
