### ISSUE TITLE
Option to disable placeholders

### ISSUE THREAD

**Issue by daviferreira** [daviferreira/medium-editor#52]
From #50:

"A simple solution is to give an option to turn off placeholder. It would be even better if it was possible to add/remove the placeHolder manually without affecting the innerHTML content. I could then add / remove it depending on my bound content..."

**Comment by nmielnik** [comment]
This is now supported via 'disablePlaceholders', though there isn't a `data-disable-placeholder` that can make the same functionality work...If we still want this, we should open a new issue.
