### ISSUE TITLE
version didn't bump in tag

### ISSUE THREAD

**Issue by phiggins42** [daviferreira/medium-editor#524]
from https://github.com/daviferreira/medium-editor/blob/4.1.0/src/js/version.js

@nmielnik et/al when you do a tag bump, do you use a different gruntfile config from in the repo?

https://github.com/daviferreira/medium-editor/blob/4.1.0/Gruntfile.js#L271

**Comment by nmielnik** [comment]
To bump the version, this is what I do:

# run `npm version major/minor/patch` (updates package.json version number)
# update bower.json with newest version
# add changes into Changes.md
# commit and push these changes
# through github, tag a new release
# run `npm publish`

Is there something else we should be doing to make sure that version gets updated as well?

**Comment by phiggins42** [comment]
so it looks like all npm version does is package.json ... for steps 1 + 2 you could run `grunt bump` (for patch revisions) or `grunt bump:minor` (3.2.1 -> 3.3.0) etc. that will hit the three files in that gruntconfig.bump list

then the rest is the same.

**Comment by daviferreira** [comment]
Do we really need a third file with version number? Maybe ```version.js``` can read from ```package.json```?

**Comment by phiggins42** [comment]
Not sure how it would or could. The same argument can be made about package.json + bower.json ... There is already a mechanism for managing an unlimited number of files with the same version reference. I guess version.js could be "generated" but it was only written the way it is because of the presence of grunt bump

**Comment by nmielnik** [comment]
@daviferreira grunt bump took care of it, looks like we can manage having this version in multiple places pretty easily

@phiggins42 great tip.
