### ISSUE TITLE
cleanTag feature

### ISSUE THREAD

**Issue by Sergiy-Babich** [daviferreira/medium-editor#526]
paste.js
cleanPaste method
calls of pasteHTML should use this.base.options as second parameter.
Otherwise cleanTag option should be ignored when pasting HTML

**Comment by phiggins42** [comment]
It is being passed along:

```
pasteHTML: function (html, options) {
            this.pasteHandler.pasteHTML(html, options);
        }
```

inside the pasteHandler the base options are available at `this.base.options` ...  

am I missing something?

**Comment by Sergiy-Babich** [comment]
paste.js:116
'this.pasteHTML('<p>' + elList.join('</p><p>') + '</p>');'

should be
'this.pasteHTML('<p>' + elList.join('</p><p>') + '</p>', this.base.options);'

**Comment by Sergiy-Babich** [comment]
paste.js:116
```javascript
this.pasteHTML('<p>' + elList.join('</p><p>') + '</p>');
```
should be
```javascript
this.pasteHTML('<p>' + elList.join('</p><p>') + '</p>', this.base.options);
```

**Comment by phiggins42** [comment]
ahhh, yes I see now. thanks for clarifying.

**Comment by nmielnik** [comment]
This was added in #535 , @Sergiy-Babich thanks for pointing this out!
