### ISSUE TITLE
Add option for custom clean RegExp

### ISSUE THREAD

**Issue by Sergiy-Babich** [daviferreira/medium-editor#529]

**Comment by phiggins42** [comment]
would #528 work for both our cases?

**Comment by Sergiy-Babich** [comment]
Some kind of. If this should allow add custom RegExp for additional cleaning that should be OK.

**Comment by phiggins42** [comment]
I can see how well-hidden that list of regexp's is :) would something like:

```
new Editor(..., { 
      pasteReplacements:[
           [new RegExp(), ""]
      ]
});
```

and then at https://github.com/daviferreira/medium-editor/blob/master/src/js/paste.js#L106

make it `replacements = createReplacements().concat(this.options.pasteReplacements || [])`

work? #528 wants to expose each of the replacements as "filters" (or some other word), as well as allow custom `function clean(text){ return cleaned(text) }` pass-through for content.

**Comment by Sergiy-Babich** [comment]
Yes, that is exactly what I want! Great.

**Comment by nmielnik** [comment]
This is now supported as of #535
