### ISSUE TITLE
Hide Placeholder on input/typing

### ISSUE THREAD

**Issue by oste** [daviferreira/medium-editor#534]
It looks like the original intention was to hide the placeholder only when the user begins typing https://github.com/daviferreira/medium-editor/issues/27#issuecomment-25487543

however this pull request is hiding it on click https://github.com/daviferreira/medium-editor/pull/339 

I agree with the original post that hiding only on input is better UX. Was this not achievable? Could this become an option? I would prefer to show the placeholder on click and only hide it once the user begins to type

**Comment by oste** [comment]
It looks like a workaround is to programmatically set the focus on the element. This still should probably be revisited however. I think more flexibility with this option would be great :+1:

**Comment by nmielnik** [comment]
@oste we haven't much time to look at this, but I agree that this makes a lot of sense as an option to be passed into medium-editor.  If you want to take a crack at a Pull Request to fix this, we can definitely try to help out and get it into the code base :smiley_cat:

**Comment by j0k3r** [comment]
Does the option `hidePlaceholderOnClik` (set by default to `true`) is ok to every one?

And when the placeholder will be an extension, the option will become `hideOnClik`.

**Comment by nmielnik** [comment]
Yeah, that sounds ok.  Maybe we should just try to make this an extension first?

**Comment by j0k3r** [comment]
Yeah, good idea :+1:

**Comment by 1u** [comment]
Nice feature!!
We didn't wind it in the documentation.

    options = {
        placeholder : {
             hideOnClick: false,
             text: "I don't hide on click"
        }
    };
