### ISSUE TITLE
Tooltips on toolbar buttons

### ISSUE THREAD

**Issue by Sergiy-Babich** [daviferreira/medium-editor#559]
Add ability to define button tooltips as title attribute.

**Comment by hellocosmin** [comment]
Why not instantiate a tooltip plugin after activating ME? This would mean you could use whatever plugin you want, not just something that would come bundled with ME.

**Comment by nmielnik** [comment]
So I opened #565 what do you think of this as a starting point?

**Comment by nmielnik** [comment]
Closing this for now, if there are additional requirements can you open them as a separate issue?
