### ISSUE TITLE
Demo page does not work via HTTPS

### ISSUE THREAD

**Issue by sashee** [daviferreira/medium-editor#560]
If you load the demo page via HTTP (https://daviferreira.github.io/medium-editor/), it does not work. It tries to load the CSS files from http:// explicitly, and the browser blocks these. The external contents' urls should start with //, and be available from https along with http.

**Comment by lurchpop** [comment]
Can confirm. I almost ditched using this lib because the demo didn't work.

**Comment by daviferreira** [comment]
I will fix this, but I wonder where did you guys find the https link sice we only use http everywhere on our docs.

**Comment by lurchpop** [comment]
Browser plugin called HTTPS everywhere.

**Comment by sashee** [comment]
Thanks for the fix! I use a HTTPS browser plugin too.
