### ISSUE TITLE
destroy method does not remove .medium-editor-hidden class

### ISSUE THREAD

**Issue by AndyOGo** [daviferreira/medium-editor#574]
This is important if you want to instantiate the Editor a second time.

As a result the `<div>` with contentEditable will be hidden

**Comment by j0k3r** [comment]
If you still have the problem, could you provide an example?
Are you using a `textarea` or a `div` when defined MediumEditor?

**Comment by AndyOGo** [comment]
I updated to the newest medium version 4.10.2
I'm using textarea

**Comment by j0k3r** [comment]
And did you still have the problem with the latest version (which is [4.11.1](https://github.com/daviferreira/medium-editor/releases/tag/4.11.1))?

**Comment by AndyOGo** [comment]
Sorry, nope.
On .destroy call the class is correctly removed from the textarea

**Comment by j0k3r** [comment]
:+1: Excellent, thanks for the feedback!

**Comment by AndyOGo** [comment]
Your welcome, thank you too!
