### ISSUE TITLE
Should the .parent option for extensions be deprecated?

### ISSUE THREAD

**Issue by nmielnik** [daviferreira/medium-editor#576]
Currently, any extension passed into MediumEditor can choose to set a `.parent` boolean on itself.  During setup, if the value of this property is true for any extension, a reference to the MediumEditor instance is assigned to the `.base` property of that extension.  Some more details are in the [documentation](https://github.com/daviferreira/medium-editor/wiki/Custom-Buttons-and-Extensions#parent-boolean--base-mediumeditor)

I'm proposing we get rid of this, and just always set `.base` to an instance of MediumEditor.  I have trouble envisioning scenarios where assigning the instance to `.base` would be problematic (except if the extension already has a `.base` property it's using for something else).

As @phiggins42 pointed out, by assuming that `.base` is always set, we can start adding some helper methods into the extension base class. Some examples:
* `.on()` and `.off()` for attaching DOM Event handlers
* `.subscribe()` and `.unsubscribe()` for custom events
* `.saveSelection()` and `.restoreSelection()`
* or any other method exposed on MediumEditor which we can just add as a helper member to each extension

Thoughts? Suggestions? Angelic Poetry :angel:?

**Comment by j0k3r** [comment]
I agree about that point :+1: 
I've written 2 extensions so far and I always use the `parent = true`.

BTW, `this.base.saveSelection()` & `this.base.restoreSelection()` are already available in extension. Or maybe I misunderstood the *helper methods* you described..

**Comment by phiggins42** [comment]
right, it's available _through_ base, but we'd be making `.base` always-on (regardless of .parent setting) ... so an "Extension" would just magically have some extra methods curried through to the .base version, but doing their own isolated tracking. eg:

instead of this.base.subscribe("editablePaste") you would `this.subscribe("editablePaste")`, and when the Extension was 'destroy'd anything that was subscribed through the self-subscribe method would be cleaned up automagically.

**Comment by nmielnik** [comment]
Yeah, @j0k3r by saying exposing helper methods, I'm meaning on the extension itself.  So instead of calling `this.base.saveSelection()` you could just call `this.saveSelection()` from the extension.

**Comment by nmielnik** [comment]
So I think it makes sense to always attach the MediumEditor instance to all extensions and deprecate the  `.parent` property.  This means all extensions will have a `.base` property as a reference to the MediumEditor instance.

Further, this means we can also stop passing the MediumEditor instance as a parameter to call to `.init()` on the extensions.

These updates will all happen in v5.0.0
