### ISSUE TITLE
Anchor preview not showing when attached to textarea

### ISSUE THREAD

**Issue by StijnMaenhaut** [daviferreira/medium-editor#582]
As the subject states: if the editor is linked to a textarea, the anchor preview won't show. 

Btw: great work!

**Comment by nmielnik** [comment]
This should be fixed via #583 and released by v4.7.0

Please let me know if you still see the issue.

**Comment by nmielnik** [comment]
This issue was also mentioned by #580

**Comment by StijnMaenhaut** [comment]
Very kind! 

Does this also include the bug that upon pasting, the forcePlainText, cleanPastedHTML, cleanTags options aren't doing what they are supposed to?

When will v4.7.0 be released?

Kind regards

**Comment by nmielnik** [comment]
v4.7.0 should be available now.
________________________________

**Comment by StijnMaenhaut** [comment]
Just downloaded, checked and everything is ok now! Thanks!
