### ISSUE TITLE
AnchorPreview doesn't clean up all its handlers on destroy.

### ISSUE THREAD

**Issue by malectro** [daviferreira/medium-editor#585]
Create an editor and destroy. Then create a second.
```
var editor = new MediumEditor(el, {buttons: ['anchor']});
editor.destroy();
editor = new MediumEditor(el, {buttons: ['anchor']});
```
Selecting any text will now throw an error here https://github.com/daviferreira/medium-editor/blob/master/src/js/extensions/anchor-preview.js#L60
```
Uncaught TypeError: Cannot read property 'classList' of undefined
```
Commenting the following line fixes the issue, but probably affects something I'm not seeing. https://github.com/daviferreira/medium-editor/blob/master/src/js/toolbar.js#L125

**Comment by j0k3r** [comment]
Could you provide a jsfiddle to reproduce? I've tried without success http://jsfiddle.net/pz4wxh55/

**Comment by malectro** [comment]
Just saw you closed this. I tried and tried to reproduce in the fiddle, but it turns out this is an issue with Angular (shocking I know) and the way it renders/rerenders the DOM. Sorry for assuming it was an issue with the editor, and thanks for responding so promptly.

**Comment by daviferreira** [comment]
:+1:  Let us know if you need any help debugging, maybe we can help out :)
