### ISSUE TITLE
Shortcut to insert a link

### ISSUE THREAD

**Issue by j0k3r** [daviferreira/medium-editor#587]
Medium.com handle <kbd>CTRL</kbd>+<kbd>K</kbd> to show the form to insert a link.
I've looked at #432 and I tried to add the `k` key in the anchor extension:

```
    function AnchorDerived() {
        this.parent = true;
        this.options = {
            name: 'anchor',
            action: 'createLink',
            aria: 'link',
            tagNames: ['a'],
            contentDefault: '<b>#</b>',
            contentFA: '<i class="fa fa-link"></i>',
            key: 'k'
        };
        this.name = 'anchor';
        this.hasForm = true;
    }
```

Sadly, when I hit <kbd>CTRL</kbd>+<kbd>K</kbd>, it calls the `createLink` action, but without params, so it fails :cry: 

![image](https://cloud.githubusercontent.com/assets/62333/7416487/f9f7faba-ef5f-11e4-8725-411e92d6311a.png)

`handleKeydown` launch the action but without params (action = `createLink`):

```
this.base.execAction(action);
```

To perfectly handle it, it should display the form.
How can I achieve that without breaking everything?

**Comment by daviferreira** [comment]
Hmmm... Maybe pass an `onKeydown` option on the button, and the `handleKeydown` method would check for it before calling `execAction`. What do you think?

**Comment by daviferreira** [comment]
Or just check for the `hasForm`property... Not sure.

**Comment by nmielnik** [comment]
I would recommend using the approach you had above, where you set the `key` option of the anchor-extension to be <kbd>K</kbd>.

Then the anchor-extension can just override the `handleKeydown` method so that it can check that <kbd>CTRL</kbd> or <kbd>COMMAND</kbd> are down and then just show the form as it would have normally (you can see that code in the `handleClick` method.

**Comment by daviferreira** [comment]
👍🏼

**Comment by j0k3r** [comment]
@daviferreira @nmielnik :+1: Good idea!

I'll submit a PR about that.
