### ISSUE TITLE
Ctrl-K shortcut for link breaks default Mac OS X text editor behavior

### ISSUE THREAD

**Issue by patrick-webs** [daviferreira/medium-editor#591]
Mac OS browsers, like other Mac applications, [support emacs-inspired keybindings for editing text](http://www.quora.com/Why-are-emacs-style-key-bindings-built-into-Cocoa-text-fields-on-Mac-OS-X). This includes Ctrl-A to go to the beginning of the line and Ctrl-K to go to the end of the line.

As a result of PR #589 , Ctrl-K no longer works in Medium on Macs, instead it creates a link if the text is highlighted or does nothing if it isn't. Ctrl-A still works.

(The original medium.com editor supports ctrl-A, but ctrl-k deletes the entire line when executed on a mac)

A good fix would be to make the link shortcut CMD-K on Mac and Ctrl-K on all other platforms (since windows and linux use Ctrl as their shortcut key).

**Comment by j0k3r** [comment]
Good point,  I never used <kbd>CTRL</kbd> + <kbd>A</kbd> or <kbd>CTRL</kbd> + <kbd>K</kbd> on my Mac to jump at the beginning or the end of the line.

@daviferreira @nmielnik Do you agree with this kind of detection ([from](http://stackoverflow.com/a/11752084/569101))?

```javascript
var key = String.fromCharCode(evt.which || evt.keyCode).toLowerCase();
var isMac = window.navigator.platform.toUpperCase().indexOf('MAC') >= 0;

if (this.options.key === key && ((isMac && evt.metaKey) || (!isMac && evt.ctrlKey))) {
    evt.preventDefault();
    evt.stopPropagation();

    this.handleClick(evt);
}
```

**Comment by daviferreira** [comment]
:+1:

**Comment by nmielnik** [comment]
I think this is a great fix, seems like we might want a helper method like `isMetaCtrlKey()` that takes in an event object, and returns true if it's metaKey on mac, or ctrlKey on non-mac.

:+1:
