### ISSUE TITLE
dist file can no longer be included in <head> section of page

### ISSUE THREAD

**Issue by yacomink** [daviferreira/medium-editor#601]
The `document.body.appendChild` introduced in `events.js` in the commit https://github.com/daviferreira/medium-editor/commit/5c24725e4bd7ca977c133884e6045982f410d66e means that this js can no longer be included in the `<head>` of a document. `document.body` will be null when this code is executed in that case.

**Comment by j0k3r** [comment]
Related to what I wrote few hours in the PR: https://github.com/daviferreira/medium-editor/pull/597/files#r30237312

**Comment by nmielnik** [comment]
This should be fixed in the 4.8.1 release
