### ISSUE TITLE
imageDraggable and custom image handling

### ISSUE THREAD

**Issue by Jiert** [daviferreira/medium-editor#608]
I'd love to overwrite the handleDrop method for dragging images into the editor, without overwriting the Medium Editor core.

Pardon my ignorance, but I don't know how to do this since I can't find it anywhere in the prototype chain after instantiating the editor.

One thing I tried was turning the imageDraggable feature OFF and capturing drag events myself, but the Medium editor still wants to do things like: `cursor: default`.

Any help would be appreciated, thanks.

**Comment by nmielnik** [comment]
So as of right now, there isn't a simple way to override the imagDraggable feature other than turning it off and attaching to the events yourself.  This wouldn't be a difficult thing to turn into an overrideable extension, so we could fix this in the near future.

You can do this by mimicking the code that attaches events [here](https://github.com/daviferreira/medium-editor/blob/master/src/js/core.js#L392)

You can subscribe to the `editableDrag` custom event (which fires each time a 'dragover' or 'dragleave' occurs over an editor) and the `editableDrop` custom event (which fires each time a 'drop' occurs over an editor) via the `subscribe()` method on the editor.

The code which currently handles dragging are the [handleDrag](https://github.com/daviferreira/medium-editor/blob/master/src/js/core.js#L142) function and the [handleDrop](https://github.com/daviferreira/medium-editor/blob/master/src/js/core.js#L154) function, so you can use those as a point of reference.

Regarding the `cursor: default`, I can't find anything in the code which would setting this property, definitely nothing associated with dragging. Can you double check where that is coming from?

**Comment by nmielnik** [comment]
A rough example of a way to override:

```javascript
var editor = new MediumEditor('.editor', {
  imageDragging: false
});

editor.subscribe('editableDrag', function (event, editable) {
  // custom drag handling
});

editor.subscribe('editableDrop', function (event, editable) {
  // custom drop handling
});
```

**Comment by nmielnik** [comment]
I moved the image-dragging into an extension, so you should be able to override the built-in behavior once #609 has been merged in and released.

**Comment by nmielnik** [comment]
Let us know if the workaround, or the image-dragging extension aren't sufficient for overriding this behavior.

Thanks for pointing this out!

**Comment by Jiert** [comment]
Awesome, thanks so much! I'll play around with this tomorrow and let you know. Cheers!

**Comment by Jiert** [comment]
Thanks again @nmielnik, the `editor.subscribe` was exactly what I was looking for.

**Comment by nmielnik** [comment]
No problem, seems like we may want to add some documentation about these custom events huh :smiling_imp:
