### ISSUE TITLE
Spellcheck stays on after destroy called on editor

### ISSUE THREAD

**Issue by nodrog** [daviferreira/medium-editor#639]
The red underlining stays on after destroy is called on the editor. 

Is this something that needs to be fixed in the editor or in the browser.

I am happy to try and fix it if anyone else is experiencing the same issues.

Many thanks

**Comment by nodrog** [comment]
Seems silly to me but after some goggling you need to reset the innerHTML on the elements
Placing:

    element.innerHTML = element.innerHTML 

inside the the elements each of the  destroy method dose the trick.

I am not sure what the overhead of this is?

I have tried other suggestions suck as focusing and then bluring the element, but not work.

**Comment by nmielnik** [comment]
Hey @nodrog thanks for finding this and opening an issue.  If you're able to validate that this fixes the issue you should definitely open a pull request.  That's a pretty interesting fix.

**Comment by j0k3r** [comment]
@nodrog you mean, you tried this solution http://stackoverflow.com/a/9325528/569101 ?

**Comment by nodrog** [comment]
@j0k3r yes tried that and had no success on chrome Version 43.0.2357.81 (64-bit)

**Comment by nmielnik** [comment]
Looks like this was fixed in #643
