### ISSUE TITLE
No Buttons, still outputs a Toolbar Arrow

### ISSUE THREAD

**Issue by michaelord** [daviferreira/medium-editor#650]
I'm passing in a blank array of buttons to the editor on init, only planning on utilizing the enter key press, and placeholder, however, when selecting text it still tried to show the toolbar (without 0 buttons).

I think there just needs to be a check for the number of buttons defined upon selecting text before choosing to show the toolbar

Cheers

**Comment by phiggins42** [comment]
makes sense. you could also disable the toolbar, no?

**Comment by michaelord** [comment]
yes, I'd completely overlooked that option though.. :(
Cheers

**Comment by nmielnik** [comment]
This is a good workaround, but it does seems like passing an empty array of buttons should infer disabled toolbar...anyone disagree?

**Comment by phiggins42** [comment]
i don't disagree ... though unsupported I am doing dynamic button showing/hiding (by way of `positionToolbar` event) ... though those buttons are _in_ the toolbar (the initial buttons list is a superset of all available, to ensure instantiation). would just want to make sure that wasn't accidentally changed.

though disabling the toolbar supercedes any `buttons` passed, so really you have to explicitly disable the toolbar one way or the other (by way of empty `buttons` or toolbar: false)?  might be worthwhile to go ahead an set the buttons array empty if the toolbar is disabled?

**Comment by nmielnik** [comment]
You bring up some good points.  I think the case where you dynamically and/remove buttons is a pretty good reason to not automatically disable the toolbar. It seems like working around that, and also trying to keep the disabled state of the toolbar up-to-date would make things needlessly complicated.

Closing this for now.
