### ISSUE TITLE
Placeholder 'false' doesn't work

### ISSUE THREAD

**Issue by bravedick** [daviferreira/medium-editor#652]
Docs:

> To disable the placeholder, set the value of the placeholder option to false:

but result is:

![screenshot 2015-05-29 12 21 36](https://cloud.githubusercontent.com/assets/988471/7879907/4dceccd2-05fd-11e5-88bf-3952cd29c10c.png)

**Comment by nmielnik** [comment]
@bravedick can you confirm what version of medium-editor you're using?  I believe this syntax for the placeholder option would have been introduced in version 4.11.0

**Comment by daviferreira** [comment]
Are you sure you are not passing false as a string? Should be: `placeholder: false`, not `placeholder: 'false'`

**Comment by bravedick** [comment]
@daviferreira sure.

@nmielnik ops, yes, i was using 4.10.1 from CDN from docs. Sorry!

<script src="https://cdnjs.cloudflare.com/ajax/libs/medium-editor/4.10.1/medium-editor.min.js"</script>
